name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
